// also double check realIDsOverlay
export const overlayDefaults = {
    showPlanetTypes: true,
    showResInf: false,
    showIdealRI: true,
    showRealID: true,
    showLore: false,
    showTokens: false
};

// Border anomaly type enablement settings
// Set to false to disable specific border anomaly types
// /public/data/border.json is generated by the AsyncTI4 sync workflow from the bot's
// data/border_anomalies, so new types appear automatically and default to enabled.
// Add an entry here only to disable one. IDs are the underscore-free uppercase form.
// Bidirectionality comes from the bot's adjacency rules (only GRAVITYWAVE is one-way).
export const borderAnomalySettings = {
    'ASTEROID': true,
    'GRAVITYWAVE': true,
    'NEBULA': true,
    'MINEFIELD': true,
    'SPATIALTEAR': true,
    'VOIDTETHER': false,
    'COREBORDER': false,
    'RIMBORDER': false,
    'YELLOW': true,
    'REDORANGE': true,
    // New types will default to true if not specified here
    // Example for disabling a type: 'TYPENAME': false,
};

// Version for debugging cache issues
export const configVersion = "1.1-with-false-values";